// yume25d に配置できるサンプル3Dモデルのカタログ。
// three.js 公式サンプル（examples/models/gltf）と Khronos glTF-Sample-Assets の
// 単一ファイル glb だけを、CDN（jsDelivr の GitHub ミラー）から読み込む。
// Draco / KTX2 など追加デコーダが要るモデルは載せない（GLTFLoader 単体で読める物のみ）。

export interface ModelCatalogEntry {
	key: string;
	/** 一覧に出す日本語名 */
	label: string;
	/** パレット・2Dエディタで使う絵文字 */
	emoji: string;
	/** キーワード検索の対象（日本語・英語を空白区切りで） */
	tags: string;
	url: string;
	source: "three.js" | "Khronos" | "MMD" | "ニコニ立体";
	/** 配布元の指定に従うクレジット表記。表示不要な素材では省く。 */
	credit?: string;
	/** 置いたときに形から当たり判定を作るか。建物や岩のような「入れない物」だけ true。
	 *  動物やキャラクターは歩き回るので false（未指定）のまま。 */
	collide?: boolean;
	/** 置いたときの大きさ（最大辺のマス数）。未指定は1。建物のように実寸が要る素材で指定する。 */
	scale?: number;
	/** モデル/モーションのフォーマット */
	format?: "glb" | "gltf" | "pmx" | "pmd" | "vmd";
	/** PMX/PMDモデル推奨のデフォルトVMDモーションURL */
	defaultMotionUrl?: string;
	/** アセットの種類 */
	category?: "model" | "motion";
}

// glTF-Sample-Assets は main ブランチ直参照（構成変更が稀なリポジトリ）。
// three.js はインストール中のバージョンに合わせたタグを固定して参照する。
const KHR =
	"https://cdn.jsdelivr.net/gh/KhronosGroup/glTF-Sample-Assets@main/Models";
const TJS =
	"https://cdn.jsdelivr.net/gh/mrdoob/three.js@r185/examples/models/gltf";
const TJS_MMD =
	"https://cdn.jsdelivr.net/gh/mrdoob/three.js@r171/examples/models/mmd";
const TAKAHIROX_MMD =
	"https://cdn.jsdelivr.net/gh/takahirox/MMDLoader-app@master";
const TAKAHIROX_MMD_VIEWER =
	"https://cdn.jsdelivr.net/gh/takahirox/mmd-viewer-js@master";
// 組み込み素材だけを置くR2バケット（unj-builtin）。一般ユーザーは書き込まず、運営が wrangler で置く。
// 画像・テキストと違って形式を問わないので、中身の種類ではなく出所で分けてある。
const BUILTIN = "https://pub-07d0a11104d64dcfbe036c7ec263ac55.r2.dev";

export const MMD_MODEL_CATALOG: ModelCatalogEntry[] = [
	{
		key: "mmd-miku-v2",
		label: "初音ミク (v2)",
		emoji: "🎤",
		tags: "mmd miku hatsune vocaloid はつねみく ミク 初音ミク PMD pmd",
		url: `${TJS_MMD}/miku/miku_v2.pmd`,
		source: "MMD",
		format: "pmd",
		defaultMotionUrl: `${TJS_MMD}/vmds/wavefile_v2.vmd`,
		category: "model",
	},
	{
		key: "mmd-kizuna-ai",
		label: "キズナアイ",
		emoji: "🎀",
		tags: "mmd kizuna ai vtuber きずなあい キズナアイ PMX pmx",
		url: `${TAKAHIROX_MMD}/models/kizunaai/kizunaai.pmx`,
		source: "MMD",
		format: "pmx",
		defaultMotionUrl: `${TAKAHIROX_MMD}/vmds/gokurakujodo.vmd`,
		category: "model",
	},
	{
		key: "mmd-kagamine-rin",
		label: "鏡音リン",
		emoji: "🍊",
		tags: "mmd rin kagamine vocaloid かがみねりん リン 鏡音リン PMD pmd",
		url: `${TAKAHIROX_MMD_VIEWER}/model/default/rin.pmd`,
		source: "MMD",
		format: "pmd",
		defaultMotionUrl: `${TJS_MMD}/vmds/wavefile_v2.vmd`,
		category: "model",
	},
	{
		key: "mmd-kagamine-ren",
		label: "鏡音レン",
		emoji: "🍌",
		tags: "mmd ren kagamine vocaloid かがみねれん レン 鏡音レン PMD pmd",
		url: `${TAKAHIROX_MMD_VIEWER}/model/default/ren.pmd`,
		source: "MMD",
		format: "pmd",
		defaultMotionUrl: `${TJS_MMD}/vmds/wavefile_v2.vmd`,
		category: "model",
	},
	{
		key: "mmd-yowane-haku",
		label: "弱音ハク",
		emoji: "🍶",
		tags: "mmd haku yowane vocaloid よわねはく ハク 弱音ハク PMD pmd",
		url: `${TAKAHIROX_MMD_VIEWER}/model/default/haku.pmd`,
		source: "MMD",
		format: "pmd",
		defaultMotionUrl: `${TJS_MMD}/vmds/wavefile_v2.vmd`,
		category: "model",
	},
	{
		key: "mmd-akita-neru",
		label: "亞北ネル",
		emoji: "📱",
		tags: "mmd neru akita vocaloid あきたねる ネル 亞北ネル PMD pmd",
		url: `${TAKAHIROX_MMD_VIEWER}/model/default/neru.pmd`,
		source: "MMD",
		format: "pmd",
		defaultMotionUrl: `${TJS_MMD}/vmds/wavefile_v2.vmd`,
		category: "model",
	},
	{
		key: "mmd-kaito",
		label: "KAITO",
		emoji: "🍨",
		tags: "mmd kaito vocaloid かいと カイト PMD pmd",
		url: `${TAKAHIROX_MMD_VIEWER}/model/default/kaito.pmd`,
		source: "MMD",
		format: "pmd",
		defaultMotionUrl: `${TJS_MMD}/vmds/wavefile_v2.vmd`,
		category: "model",
	},
	{
		key: "mmd-meiko",
		label: "MEIKO",
		emoji: "🍷",
		tags: "mmd meiko vocaloid めいこ メイコ PMD pmd",
		url: `${TAKAHIROX_MMD_VIEWER}/model/default/MEIKO.pmd`,
		source: "MMD",
		format: "pmd",
		defaultMotionUrl: `${TJS_MMD}/vmds/wavefile_v2.vmd`,
		category: "model",
	},
	{
		key: "mmd-sakine-meiko",
		label: "咲音メイコ",
		emoji: "🎙️",
		tags: "mmd sakine meiko vocaloid さきねめいこ 咲音メイコ PMD pmd",
		url: `${TAKAHIROX_MMD_VIEWER}/model/default/meiko_sakine.pmd`,
		source: "MMD",
		format: "pmd",
		defaultMotionUrl: `${TJS_MMD}/vmds/wavefile_v2.vmd`,
		category: "model",
	},
	{
		key: "mmd-dummy",
		label: "ダミーボーン",
		emoji: "🦴",
		tags: "mmd dummy bone だみー ダミーボーン PMD pmd",
		url: `${TAKAHIROX_MMD_VIEWER}/model/default/dummy.pmd`,
		source: "MMD",
		format: "pmd",
		defaultMotionUrl: `${TJS_MMD}/vmds/wavefile_v2.vmd`,
		category: "model",
	},
	{
		key: "mmd-miku-base",
		label: "初音ミク (標準)",
		emoji: "🎤",
		tags: "mmd miku hatsune vocaloid はつねみく ミク 初音ミク PMD pmd",
		url: `${TAKAHIROX_MMD_VIEWER}/model/default/miku.pmd`,
		source: "MMD",
		format: "pmd",
		defaultMotionUrl: `${TJS_MMD}/vmds/wavefile_v2.vmd`,
		category: "model",
	},
	{
		key: "mmd-miku-metal",
		label: "初音ミク (メタル)",
		emoji: "🎸",
		tags: "mmd miku hatsune vocaloid metal はつねみく ミク 初音ミク PMD pmd",
		url: `${TAKAHIROX_MMD_VIEWER}/model/default/miku_m.pmd`,
		source: "MMD",
		format: "pmd",
		defaultMotionUrl: `${TJS_MMD}/vmds/wavefile_v2.vmd`,
		category: "model",
	},
	{
		key: "mmd-kagamine-rin-act2",
		label: "鏡音リン (ACT2)",
		emoji: "🍊",
		tags: "mmd rin kagamine vocaloid act2 かがみねりん リン 鏡音リン PMD pmd",
		url: `${TAKAHIROX_MMD_VIEWER}/model/default/rin_act2.pmd`,
		source: "MMD",
		format: "pmd",
		defaultMotionUrl: `${TJS_MMD}/vmds/wavefile_v2.vmd`,
		category: "model",
	},
];

export const MMD_MOTION_CATALOG: ModelCatalogEntry[] = [
	{
		key: "vmd-wavefile-dance",
		label: "Wavefile (ダンス)",
		emoji: "💃",
		tags: "vmd wavefile dance motion モーション ダンス",
		url: `${TJS_MMD}/vmds/wavefile_v2.vmd`,
		source: "MMD",
		format: "vmd",
		category: "motion",
	},
	{
		key: "vmd-wavefile-camera",
		label: "Wavefile (カメラ)",
		emoji: "🎥",
		tags: "vmd wavefile camera motion カメラ 演出",
		url: `${TJS_MMD}/vmds/wavefile_camera.vmd`,
		source: "MMD",
		format: "vmd",
		category: "motion",
	},
	{
		key: "vmd-gokurakujodo-dance",
		label: "極楽浄土 (ダンス)",
		emoji: "✨",
		tags: "vmd gokurakujodo dance motion 極楽浄土 ダンス モーション",
		url: `${TAKAHIROX_MMD}/vmds/gokurakujodo.vmd`,
		source: "MMD",
		format: "vmd",
		category: "motion",
	},
	{
		key: "vmd-walk",
		label: "歩行モーション",
		emoji: "🚶",
		tags: "vmd walk motion 歩行 モーション",
		url: `https://raw.githubusercontent.com/bear0830/mmd/master/walk.vmd`,
		source: "MMD",
		format: "vmd",
		category: "motion",
	},
	{
		key: "vmd-sample-1",
		label: "モーション 1",
		emoji: "🕺",
		tags: "vmd motion sample 1 モーション",
		url: `https://raw.githubusercontent.com/bear0830/mmd/master/1.vmd`,
		source: "MMD",
		format: "vmd",
		category: "motion",
	},
	{
		key: "vmd-sample-2",
		label: "モーション 2",
		emoji: "👯",
		tags: "vmd motion sample 2 モーション",
		url: `https://raw.githubusercontent.com/bear0830/mmd/master/2.vmd`,
		source: "MMD",
		format: "vmd",
		category: "motion",
	},
	{
		key: "vmd-sample-3",
		label: "モーション 3",
		emoji: "💃",
		tags: "vmd motion sample 3 モーション",
		url: `https://raw.githubusercontent.com/bear0830/mmd/master/3.vmd`,
		source: "MMD",
		format: "vmd",
		category: "motion",
	},
	{
		key: "vmd-sample-4",
		label: "モーション 4",
		emoji: "✨",
		tags: "vmd motion sample 4 モーション",
		url: `https://raw.githubusercontent.com/bear0830/mmd/master/4.vmd`,
		source: "MMD",
		format: "vmd",
		category: "motion",
	},
	{
		key: "vmd-sample-5",
		label: "モーション 5",
		emoji: "🎵",
		tags: "vmd motion sample 5 モーション",
		url: `https://raw.githubusercontent.com/bear0830/mmd/master/5.vmd`,
		source: "MMD",
		format: "vmd",
		category: "motion",
	},
	{
		key: "vmd-sample-6",
		label: "モーション 6",
		emoji: "🎶",
		tags: "vmd motion sample 6 モーション",
		url: `https://raw.githubusercontent.com/bear0830/mmd/master/6.vmd`,
		source: "MMD",
		format: "vmd",
		category: "motion",
	},
	{
		key: "vmd-sample-7",
		label: "モーション 7",
		emoji: "🩰",
		tags: "vmd motion sample 7 モーション",
		url: `https://raw.githubusercontent.com/bear0830/mmd/master/7.vmd`,
		source: "MMD",
		format: "vmd",
		category: "motion",
	},
	{
		key: "vmd-sample-8",
		label: "モーション 8",
		emoji: "👯‍♀️",
		tags: "vmd motion sample 8 モーション",
		url: `https://raw.githubusercontent.com/bear0830/mmd/master/8.vmd`,
		source: "MMD",
		format: "vmd",
		category: "motion",
	},
	{
		key: "vmd-sample-9",
		label: "モーション 9",
		emoji: "🤸",
		tags: "vmd motion sample 9 モーション",
		url: `https://raw.githubusercontent.com/bear0830/mmd/master/9.vmd`,
		source: "MMD",
		format: "vmd",
		category: "motion",
	},
	{
		key: "vmd-sample-10",
		label: "モーション 10",
		emoji: "🌟",
		tags: "vmd motion sample 10 モーション",
		url: `https://raw.githubusercontent.com/bear0830/mmd/master/10.vmd`,
		source: "MMD",
		format: "vmd",
		category: "motion",
	},
	{
		key: "vmd-sample-11",
		label: "モーション 11",
		emoji: "💫",
		tags: "vmd motion sample 11 モーション",
		url: `https://raw.githubusercontent.com/bear0830/mmd/master/11.vmd`,
		source: "MMD",
		format: "vmd",
		category: "motion",
	},
	{
		key: "vmd-sample-12",
		label: "モーション 12",
		emoji: "⭐",
		tags: "vmd motion sample 12 モーション",
		url: `https://raw.githubusercontent.com/bear0830/mmd/master/12.vmd`,
		source: "MMD",
		format: "vmd",
		category: "motion",
	},
	{
		key: "vmd-sample-13",
		label: "モーション 13",
		emoji: "🔥",
		tags: "vmd motion sample 13 モーション",
		url: `https://raw.githubusercontent.com/bear0830/mmd/master/13.vmd`,
		source: "MMD",
		format: "vmd",
		category: "motion",
	},
	{
		key: "vmd-sample-14",
		label: "モーション 14",
		emoji: "⚡",
		tags: "vmd motion sample 14 モーション",
		url: `https://raw.githubusercontent.com/bear0830/mmd/master/14.vmd`,
		source: "MMD",
		format: "vmd",
		category: "motion",
	},
	{
		key: "vmd-sample-15",
		label: "モーション 15",
		emoji: "🎉",
		tags: "vmd motion sample 15 モーション",
		url: `https://raw.githubusercontent.com/bear0830/mmd/master/15.vmd`,
		source: "MMD",
		format: "vmd",
		category: "motion",
	},
	{
		key: "vmd-sample-16",
		label: "モーション 16",
		emoji: "🎊",
		tags: "vmd motion sample 16 モーション",
		url: `https://raw.githubusercontent.com/bear0830/mmd/master/16.vmd`,
		source: "MMD",
		format: "vmd",
		category: "motion",
	},
	{
		key: "vmd-sample-17",
		label: "モーション 17",
		emoji: "🎈",
		tags: "vmd motion sample 17 モーション",
		url: `https://raw.githubusercontent.com/bear0830/mmd/master/17.vmd`,
		source: "MMD",
		format: "vmd",
		category: "motion",
	},
	{
		key: "vmd-sample-18",
		label: "モーション 18",
		emoji: "💨",
		tags: "vmd motion sample 18 モーション",
		url: `https://raw.githubusercontent.com/bear0830/mmd/master/18.vmd`,
		source: "MMD",
		format: "vmd",
		category: "motion",
	},
	{
		key: "vmd-sample-19",
		label: "モーション 19",
		emoji: "🌪️",
		tags: "vmd motion sample 19 モーション",
		url: `https://raw.githubusercontent.com/bear0830/mmd/master/19.vmd`,
		source: "MMD",
		format: "vmd",
		category: "motion",
	},
	{
		key: "vmd-sample-20",
		label: "モーション 20",
		emoji: "🎀",
		tags: "vmd motion sample 20 モーション",
		url: `https://raw.githubusercontent.com/bear0830/mmd/master/20.vmd`,
		source: "MMD",
		format: "vmd",
		category: "motion",
	},
	{
		key: "vmd-sample-21",
		label: "モーション 21",
		emoji: "🎭",
		tags: "vmd motion sample 21 モーション",
		url: `https://raw.githubusercontent.com/bear0830/mmd/master/21.vmd`,
		source: "MMD",
		format: "vmd",
		category: "motion",
	},
	{
		key: "vmd-sample-22",
		label: "モーション 22",
		emoji: "💃",
		tags: "vmd motion sample 22 モーション",
		url: `https://raw.githubusercontent.com/bear0830/mmd/master/22.vmd`,
		source: "MMD",
		format: "vmd",
		category: "motion",
	},
	{
		key: "vmd-sample-23",
		label: "モーション 23",
		emoji: "🕺",
		tags: "vmd motion sample 23 モーション",
		url: `https://raw.githubusercontent.com/bear0830/mmd/master/23.vmd`,
		source: "MMD",
		format: "vmd",
		category: "motion",
	},
	{
		key: "vmd-sample-24",
		label: "モーション 24",
		emoji: "🤸‍♂️",
		tags: "vmd motion sample 24 モーション",
		url: `https://raw.githubusercontent.com/bear0830/mmd/master/24.vmd`,
		source: "MMD",
		format: "vmd",
		category: "motion",
	},
];

export const MODEL_CATALOG: ModelCatalogEntry[] = [
	// MMD_MODEL_CATALOG はここに含めない（PMD/PMXはGLTFLoaderで読めないため、
	// mmo3dのbabylon-mmd専用。Mmo3dEditorPanel.tsxが直接参照する）。
	{
		// ニコニ立体 td95608「ガバ立教大学」(novichok)。著作表示不要・商用可・改変可・再配布可。
		// 配布は OBJ+MTL+PNG なので、GLTFLoader で読めるよう GLB へ変換して置いてある。
		key: "rikkyo",
		label: "赤レンガの本館",
		emoji: "🏛️",
		tags: "building 建物 校舎 大学 レンガ 洋館 立教 rikkyo",
		url: `${BUILTIN}/models/rikkyo.glb`,
		source: "ニコニ立体",
		credit: "ガバ立教大学 / novichok",
		format: "glb",
		collide: true,
		scale: 14,
	},
	{
		// 同じ作者の冬版（td95609）。UV座標が別物なので通常版とはテクスチャを共有できない。
		key: "rikkyo-winter",
		label: "赤レンガの本館（冬）",
		emoji: "🏛️",
		tags: "building 建物 校舎 大学 レンガ 洋館 立教 rikkyo 冬 雪 winter snow",
		url: `${BUILTIN}/models/rikkyo-winter.glb`,
		source: "ニコニ立体",
		credit: "ガバ立教大学（冬） / novichok",
		format: "glb",
		collide: true,
		scale: 14,
	},
	// ローポリの家6種（td96137, まつかりすく）。CC0。配布物は6軒を並べた1ファイルなので、
	// 1軒ずつ置けるようノード単位へ分割し、テクスチャを512pxへ落としてある（1軒32KB）。
	...([1, 2, 3, 4, 5, 6].map((n) => ({
		key: `house${n}`,
		label: `家 ${n}`,
		emoji: "🏠",
		tags: `house 家 住宅 民家 建物 街 town ${n}`,
		url: `${BUILTIN}/models/house${n}.glb`,
		source: "ニコニ立体" as const,
		credit: "家 ローポリ3Dモデル / まつかりすく (CC0)",
		format: "glb" as const,
		collide: true,
		scale: 4,
	})) as ModelCatalogEntry[]),
	// ローポリ地形4種（td87473-5 / td87464, 遠藤 現終(仮名)）。要クレジット表示。
	// テクスチャ無しの単色メッシュ。頂点を量子化して 1.7MB→1.2MB にしてある。
	...([
		["rock", "岩山", "🪨", "rock 岩 岩山 山 崖"],
		["green", "野山", "⛰️", "green 野山 山 草 丘"],
		["sand", "砂山", "🏜️", "sand 砂 砂山 山 砂漠 desert"],
		["snow", "雪山", "🏔️", "snow 雪 雪山 山 氷 winter"],
	].map(([k, label, emoji, tags]) => ({
		key: `mountain-${k}`,
		label: `ローポリ ${label}`,
		emoji,
		tags: `${tags} 地形 terrain 風景`,
		url: `${BUILTIN}/models/mountain-${k}.glb`,
		source: "ニコニ立体" as const,
		credit: "ローポリ山シリーズ / 遠藤 現終(仮名)",
		format: "glb" as const,
		collide: true,
		scale: 20,
	})) as ModelCatalogEntry[]),
	// 小物・風景。いずれも再配布可・改変可の素材。
	{
		// td86155「木 - マテリアル無し」(遠藤 現終(仮名))。題名どおり色が付いていないので、
		// 幹と葉へ色だけ入れてある（頂点データには触れていない）。要クレジット表示。
		key: "tree",
		label: "木",
		emoji: "🌳",
		tags: "tree 木 樹 森 林 植物 風景 nature",
		url: `${BUILTIN}/models/tree.glb`,
		source: "ニコニ立体",
		credit: "木 - マテリアル無し / 遠藤 現終(仮名)",
		format: "glb",
		collide: true,
		scale: 6,
	},
	{
		key: "arcade",
		label: "駄菓子屋のゲーム筐体",
		emoji: "🕹️",
		tags: "arcade ゲーム 筐体 駄菓子屋 レトロ 昭和 家具",
		url: `${BUILTIN}/models/arcade.glb`,
		source: "ニコニ立体",
		credit: "昔駄菓子屋にあったゲーム筐体 / rerofumi",
		format: "glb",
		collide: true,
		scale: 1.2,
	},
	{
		key: "chair",
		label: "丸イス",
		emoji: "🪑",
		tags: "chair イス 椅子 丸イス 家具 室内",
		url: `${BUILTIN}/models/chair.glb`,
		source: "ニコニ立体",
		credit: "丸イス / rerofumi",
		format: "glb",
		scale: 0.8,
	},
	{
		key: "shelf",
		label: "本棚",
		emoji: "📚",
		tags: "shelf 本棚 棚 家具 室内 bookshelf",
		url: `${BUILTIN}/models/shelf.glb`,
		source: "ニコニ立体",
		credit: "本棚・ブックシェルフ / 冷やし担々麺",
		format: "glb",
		collide: true,
		scale: 2,
	},
	{
		key: "duck",
		label: "アヒル",
		emoji: "🦆",
		tags: "duck bird あひる とり 鳥 どうぶつ 動物",
		url: `${KHR}/Duck/glTF-Binary/Duck.glb`,
		source: "Khronos",
	},
	{
		key: "fox",
		label: "キツネ",
		emoji: "🦊",
		tags: "fox きつね 狐 どうぶつ 動物",
		url: `${KHR}/Fox/glTF-Binary/Fox.glb`,
		source: "Khronos",
	},
	{
		key: "horse",
		label: "ウマ",
		emoji: "🐴",
		tags: "horse うま 馬 どうぶつ 動物",
		url: `${TJS}/Horse.glb`,
		source: "three.js",
	},
	{
		key: "flamingo",
		label: "フラミンゴ",
		emoji: "🦩",
		tags: "flamingo bird ふらみんご とり 鳥",
		url: `${TJS}/Flamingo.glb`,
		source: "three.js",
	},
	{
		key: "parrot",
		label: "オウム",
		emoji: "🦜",
		tags: "parrot bird おうむ とり 鳥",
		url: `${TJS}/Parrot.glb`,
		source: "three.js",
	},
	{
		key: "stork",
		label: "コウノトリ",
		emoji: "🕊️",
		tags: "stork bird こうのとり とり 鳥",
		url: `${TJS}/Stork.glb`,
		source: "three.js",
	},
	{
		key: "fish",
		label: "バラマンディ（魚）",
		emoji: "🐟",
		tags: "fish barramundi さかな 魚",
		url: `${KHR}/BarramundiFish/glTF-Binary/BarramundiFish.glb`,
		source: "Khronos",
	},
	{
		key: "cesium-man",
		label: "ヒト（CesiumMan）",
		emoji: "🧍",
		tags: "man human ひと 人 人間",
		url: `${KHR}/CesiumMan/glTF-Binary/CesiumMan.glb`,
		source: "Khronos",
	},
	{
		key: "soldier",
		label: "兵士",
		emoji: "💂",
		tags: "soldier human へいし 兵士 人",
		url: `${TJS}/Soldier.glb`,
		source: "three.js",
	},
	{
		key: "robot-expressive",
		label: "ロボット",
		emoji: "🤖",
		tags: "robot ろぼっと ロボット",
		url: `${TJS}/RobotExpressive/RobotExpressive.glb`,
		source: "three.js",
	},
	{
		key: "robot-brainstem",
		label: "ロボット（BrainStem）",
		emoji: "🦾",
		tags: "robot ろぼっと ロボット SF",
		url: `${KHR}/BrainStem/glTF-Binary/BrainStem.glb`,
		source: "Khronos",
	},
	{
		key: "milk-truck",
		label: "ミルクトラック",
		emoji: "🚚",
		tags: "truck car とらっく 車 くるま のりもの 乗り物",
		url: `${KHR}/CesiumMilkTruck/glTF-Binary/CesiumMilkTruck.glb`,
		source: "Khronos",
	},
	{
		key: "toy-car",
		label: "おもちゃの車",
		emoji: "🚗",
		tags: "toy car くるま 車 おもちゃ のりもの 乗り物",
		url: `${KHR}/ToyCar/glTF-Binary/ToyCar.glb`,
		source: "Khronos",
	},
	{
		key: "avocado",
		label: "アボカド",
		emoji: "🥑",
		tags: "avocado food あぼかど たべもの 食べ物 果物",
		url: `${KHR}/Avocado/glTF-Binary/Avocado.glb`,
		source: "Khronos",
	},
	{
		key: "water-bottle",
		label: "水筒",
		emoji: "🍶",
		tags: "bottle water すいとう 水筒 ボトル",
		url: `${KHR}/WaterBottle/glTF-Binary/WaterBottle.glb`,
		source: "Khronos",
	},
	{
		key: "boombox",
		label: "ラジカセ",
		emoji: "📻",
		tags: "boombox radio らじかせ 音楽 ラジオ",
		url: `${KHR}/BoomBox/glTF-Binary/BoomBox.glb`,
		source: "Khronos",
	},
	{
		key: "lantern",
		label: "街灯ランタン",
		emoji: "🏮",
		tags: "lantern light らんたん あかり 街灯",
		url: `${KHR}/Lantern/glTF-Binary/Lantern.glb`,
		source: "Khronos",
	},
	{
		key: "antique-camera",
		label: "アンティークカメラ",
		emoji: "📷",
		tags: "camera かめら カメラ",
		url: `${KHR}/AntiqueCamera/glTF-Binary/AntiqueCamera.glb`,
		source: "Khronos",
	},
	{
		key: "damaged-helmet",
		label: "ダメージヘルメット",
		emoji: "🪖",
		tags: "helmet SF へるめっと ヘルメット",
		url: `${KHR}/DamagedHelmet/glTF-Binary/DamagedHelmet.glb`,
		source: "Khronos",
	},
	{
		key: "sheen-chair",
		label: "椅子",
		emoji: "🪑",
		tags: "chair いす 椅子 家具",
		url: `${KHR}/SheenChair/glTF-Binary/SheenChair.glb`,
		source: "Khronos",
	},
	{
		key: "corset",
		label: "コルセット",
		emoji: "👗",
		tags: "corset こるせっと 服 家具",
		url: `${KHR}/Corset/glTF-Binary/Corset.glb`,
		source: "Khronos",
	},
	{
		key: "box-textured",
		label: "テクスチャ箱",
		emoji: "📦",
		tags: "box はこ 箱",
		url: `${KHR}/BoxTextured/glTF-Binary/BoxTextured.glb`,
		source: "Khronos",
	},

	// Three.js examples additions
	{
		key: "dragon",
		label: "ドラゴン",
		emoji: "🐉",
		tags: "dragon monster fantasy creature どらごん 竜 龍 モンスター ファンタジー",
		url: `${TJS}/DragonAttenuation.glb`,
		source: "three.js",
	},
	{
		key: "flower",
		label: "花",
		emoji: "🌸",
		tags: "flower plant nature garden はな 花 植物 自然",
		url: `${TJS}/Flower/Flower.glb`,
		source: "three.js",
	},
	{
		key: "statue-head",
		label: "彫像（頭部）",
		emoji: "🗿",
		tags: "statue head face bust sculpture human ちょうぞう 頭部 顔 人間 彫刻",
		url: `${TJS}/LeePerrySmith/LeePerrySmith.glb`,
		source: "three.js",
	},
	{
		key: "michelle",
		label: "女性（ミシェル）",
		emoji: "💃",
		tags: "woman human character dance michelle じょせい 女性 人 キャラクター ダンス",
		url: `${TJS}/Michelle.glb`,
		source: "three.js",
	},
	{
		key: "nefertiti",
		label: "ネフェルティティの胸像",
		emoji: "🏺",
		tags: "nefertiti bust statue sculpture egypt ねふぇるてぃてぃ 胸像 彫刻 エジプト",
		url: `${TJS}/Nefertiti/Nefertiti.glb`,
		source: "three.js",
	},
	{
		key: "ion-drive",
		label: "イオンエンジン",
		emoji: "🚀",
		tags: "ion drive engine space rocket sf いおん えんじん 宇宙 ロケット 乗り物",
		url: `${TJS}/PrimaryIonDrive.glb`,
		source: "three.js",
	},
	{
		key: "xbot",
		label: "ロボット（Xボット）",
		emoji: "🤖",
		tags: "robot android xbot character ろぼっと ロボット アンドロイド キャラクター",
		url: `${TJS}/Xbot.glb`,
		source: "three.js",
	},
	{
		key: "coffee-mug",
		label: "マグカップ",
		emoji: "☕",
		tags: "coffee mug cup drink kitchen まぐかっぷ コップ 食器 カフェ",
		url: `${TJS}/coffeeMug.glb`,
		source: "three.js",
	},
	{
		key: "dungeon",
		label: "ダンジョン",
		emoji: "🏰",
		tags: "dungeon room castle map stage だんじょん 城 部屋 マップ ステージ",
		url: `${TJS}/dungeon_warkarma.glb`,
		source: "three.js",
	},
	{
		key: "rpm-avatar",
		label: "アバター（ReadyPlayerMe）",
		emoji: "👤",
		tags: "avatar character human rpm あばたー 人物 キャラクター",
		url: `${TJS}/readyplayer.me.glb`,
		source: "three.js",
	},
	{
		key: "spaceship-hallway",
		label: "宇宙船の通路",
		emoji: "🌌",
		tags: "spaceship hallway corridor sf room うちゅうせん 通路 部屋",
		url: `${TJS}/space_ship_hallway.glb`,
		source: "three.js",
	},
	{
		key: "steampunk-camera",
		label: "スチームパンクカメラ",
		emoji: "🎥",
		tags: "steampunk camera antique machine すちーむぱんく カメラ 機械",
		url: `${TJS}/steampunk_camera.glb`,
		source: "three.js",
	},

	// Khronos glTF-Sample-Assets additions
	{
		key: "chess-game",
		label: "チェス",
		emoji: "♟️",
		tags: "chess board game play play board ちぇす ゲーム 盤面 遊び",
		url: `${KHR}/ABeautifulGame/glTF-Binary/ABeautifulGame.glb`,
		source: "Khronos",
	},
	{
		key: "car-concept",
		label: "コンセプトカー",
		emoji: "🏎️",
		tags: "car vehicle sports concept race かー 車 乗り物 レース",
		url: `${KHR}/CarConcept/glTF-Binary/CarConcept.glb`,
		source: "Khronos",
	},
	{
		key: "chair-luxury",
		label: "豪華な椅子",
		emoji: "🪑",
		tags: "chair luxury furniture gold royal いす 椅子 家具 ゴールド",
		url: `${KHR}/ChairDamaskPurplegold/glTF-Binary/ChairDamaskPurplegold.glb`,
		source: "Khronos",
	},
	{
		key: "chronograph-watch",
		label: "腕時計",
		emoji: "⌚",
		tags: "watch clock chronograph luxury gold うでどけい 時計 アクセサリー",
		url: `${KHR}/ChronographWatch/glTF-Binary/ChronographWatch.glb`,
		source: "Khronos",
	},
	{
		key: "commercial-refrigerator",
		label: "業務用冷蔵庫",
		emoji: "🧊",
		tags: "refrigerator fridge shop store appliance れいぞうこ 冷蔵庫 店舗 家電",
		url: `${KHR}/CommercialRefrigerator/glTF-Binary/CommercialRefrigerator.glb`,
		source: "Khronos",
	},
	{
		key: "potted-plant",
		label: "観葉植物",
		emoji: "🪴",
		tags: "plant pot green leaf houseplant しょくぶつ 植物 鉢植え 植木",
		url: `${KHR}/DiffuseTransmissionPlant/glTF-Binary/DiffuseTransmissionPlant.glb`,
		source: "Khronos",
	},
	{
		key: "teacup",
		label: "ティーカップ",
		emoji: "🍵",
		tags: "tea cup glass drink teacup 紅茶 コップ カフェ ティータイム",
		url: `${KHR}/DiffuseTransmissionTeacup/glTF-Binary/DiffuseTransmissionTeacup.glb`,
		source: "Khronos",
	},
	{
		key: "sofa-velvet",
		label: "ベルベットソファ",
		emoji: "🛋️",
		tags: "sofa couch chair furniture velvet そふぁ ソファー 家具",
		url: `${KHR}/GlamVelvetSofa/glTF-Binary/GlamVelvetSofa.glb`,
		source: "Khronos",
	},
	{
		key: "candle-holder",
		label: "キャンドルホルダー",
		emoji: "🕯️",
		tags: "candle holder light glass candle ろうそく 蝋燭 キャンドル",
		url: `${KHR}/GlassHurricaneCandleHolder/glTF-Binary/GlassHurricaneCandleHolder.glb`,
		source: "Khronos",
	},
	{
		key: "vase-flowers",
		label: "花瓶の花",
		emoji: "💐",
		tags: "vase flower glass plants garden かびん 花 花瓶 植物",
		url: `${KHR}/GlassVaseFlowers/glTF-Binary/GlassVaseFlowers.glb`,
		source: "Khronos",
	},
	{
		key: "olives-dish",
		label: "オリーブの皿",
		emoji: "🫒",
		tags: "olive dish plate food table おりーぶ 皿 たべもの 食べ物",
		url: `${KHR}/IridescentDishWithOlives/glTF-Binary/IridescentDishWithOlives.glb`,
		source: "Khronos",
	},
	{
		key: "sneaker",
		label: "スニーカー",
		emoji: "👟",
		tags: "shoe sneaker fashion wear sports すにーかー 靴 服飾 スポーツ",
		url: `${KHR}/MaterialsVariantsShoe/glTF-Binary/MaterialsVariantsShoe.glb`,
		source: "Khronos",
	},
	{
		key: "mosquito-amber",
		label: "琥珀の中の蚊",
		emoji: "💎",
		tags: "mosquito amber fossil bug insect dinosaur こはく 琥珀 虫 化石",
		url: `${KHR}/MosquitoInAmber/glTF-Binary/MosquitoInAmber.glb`,
		source: "Khronos",
	},
	{
		key: "pot-coals",
		label: "炭火の鉢",
		emoji: "🔥",
		tags: "pot coal fire charcoal heater camp すみび 炭火 火 鉢 キャンプ",
		url: `${KHR}/PotOfCoals/glTF-Binary/PotOfCoals.glb`,
		source: "Khronos",
	},
	{
		key: "mannequin",
		label: "マネキン",
		emoji: "🧍",
		tags: "mannequin figure human posture dummy まねきん 人形 素体",
		url: `${KHR}/RiggedFigure/glTF-Binary/RiggedFigure.glb`,
		source: "Khronos",
	},
	{
		key: "skull",
		label: "ドクロ（頭蓋骨）",
		emoji: "💀",
		tags: "skull bone death head zombie horror がいこつ 骸骨 骨 ホラー",
		url: `${KHR}/ScatteringSkull/glTF-Binary/ScatteringSkull.glb`,
		source: "Khronos",
	},
	{
		key: "sofa-leather",
		label: "レザーソファ",
		emoji: "🛋️",
		tags: "sofa leather furniture chair couch そふぁ ソファー 家具",
		url: `${KHR}/SheenWoodLeatherSofa/glTF-Binary/SheenWoodLeatherSofa.glb`,
		source: "Khronos",
	},
	{
		key: "silk-cushion",
		label: "シルクのクッション",
		emoji: "🪘",
		tags: "pouf cushion silk furniture seat くっしょん クッション 家具",
		url: `${KHR}/SpecularSilkPouf/glTF-Binary/SpecularSilkPouf.glb`,
		source: "Khronos",
	},
	{
		key: "sunglasses",
		label: "サングラス",
		emoji: "🕶️",
		tags: "sunglasses glasses fashion wear eye さんぐらす 眼鏡 メガネ",
		url: `${KHR}/SunglassesKhronos/glTF-Binary/SunglassesKhronos.glb`,
		source: "Khronos",
	},
	{
		key: "virtual-city",
		label: "バーチャルシティ",
		emoji: "🏙️",
		tags: "city town map virtual miniature landscape まち 街 都市 マップ",
		url: `${KHR}/VirtualCity/glTF-Binary/VirtualCity.glb`,
		source: "Khronos",
	},
];

/** キーワード検索：空白区切りの全トークンが label/tags/key のどれかに含まれる物を返す。 */
export const searchModels = (query: string): ModelCatalogEntry[] => {
	const tokens = query.trim().toLowerCase().split(/\s+/).filter(Boolean);
	if (!tokens.length) return MODEL_CATALOG;
	return MODEL_CATALOG.filter((m) => {
		const hay = `${m.label} ${m.tags} ${m.key}`.toLowerCase();
		return tokens.every((t) => hay.includes(t));
	});
};
