import { Post } from "./types";

export const INITIAL_POSTS: Post[] = [
  {
    id: 1,
    name: "名無しaB3",
    time: "3時間前",
    content: "#お絵描き\n今日の落書き 天気いいから外でスケッチした",
    likes: 42,
    dislikes: 0,
    liked: false,
    disliked: false,
    repliesCount: 12,
    reposts: 5,
    reposted: false,
    hasImage: true,
    imageSrc: "sketch_01.png",
    imageAlt: "公園のベンチで描いたスケッチ",
    avatarColor: "from-sky-400 to-blue-500",
    hasCollabButton: true,
    heartsTotal: 320,
    replies: [
      { id: 101, name: "名無しxY7", content: "いい感じ！色使いが好き", time: "2時間前" },
      { id: 102, name: "名無しQw3", content: "外で描くの気持ちいいよね", time: "1時間前" }
    ]
  },
  {
    id: 2,
    name: "名無しR9k",
    time: "5時間前",
    content: "今週の #ゲーム 進捗\nステージ3のボス戦やっと実装できた\nあとは調整だけどバグが取れない…",
    likes: 18,
    dislikes: 3,
    liked: false,
    disliked: false,
    repliesCount: 7,
    reposts: 1,
    reposted: false,
    hasGame: true,
    avatarColor: "from-red-500 to-rose-600",
    hasCollabButton: true,
    heartsTotal: 95,
    replies: [
      { id: 103, name: "名無しTp4", content: "デバッグ頑張って！", time: "4時間前" }
    ]
  },
  {
    id: 3,
    name: "名無しLm8",
    time: "8時間前",
    content: "朝起きたら雪積もっててびっくりした\nもう春だと思ってたのに",
    likes: 56,
    dislikes: 2,
    liked: false,
    disliked: false,
    repliesCount: 19,
    reposts: 8,
    reposted: false,
    hasImage: true,
    imageSrc: "snow_morning.jpg",
    imageAlt: "朝の雪景色",
    avatarColor: "from-gray-300 to-slate-400",
    hasCollabButton: false,
    heartsTotal: 612,
    replies: [
      { id: 104, name: "名無しDf2", content: "こっちはもう桜咲きそう", time: "7時間前" },
      { id: 105, name: "名無しGh6", content: "地域によって違うよね〜", time: "6時間前" },
      { id: 106, name: "名無しJk9", content: "写真綺麗！", time: "5時間前" }
    ]
  },
  {
    id: 4,
    name: "名無しVc1",
    time: "12時間前",
    content: "#お絵描き\n久しぶりに描いた 練習帳",
    likes: 33,
    dislikes: 1,
    liked: false,
    disliked: false,
    repliesCount: 9,
    reposts: 3,
    reposted: false,
    hasImage: true,
    imageSrc: "practice_sketch.png",
    imageAlt: "キャラクターの表情練習",
    avatarColor: "from-purple-400 to-violet-500",
    hasCollabButton: true,
    heartsTotal: 278,
    replies: []
  },
  {
    id: 5,
    name: "名無しBn5",
    time: "1日前",
    content: "作業用BGM何聴いてる？\n最近はlofiばかり",
    likes: 21,
    dislikes: 0,
    liked: false,
    disliked: false,
    repliesCount: 31,
    reposts: 2,
    reposted: false,
    avatarColor: "from-emerald-400 to-teal-500",
    hasCollabButton: false,
    heartsTotal: 45,
    replies: [
      { id: 107, name: "名無しWx8", content: "自分は環境音派", time: "20時間前" },
      { id: 108, name: "名無しYz2", content: "シティポップおすすめ", time: "18時間前" }
    ]
  },
  {
    id: 6,
    name: "名無しQp7",
    time: "2日前",
    content: "#お絵描き #ゲーム\nドット絵の練習中\nキャラチップ自作すると愛着湧くね",
    likes: 67,
    dislikes: 4,
    liked: false,
    disliked: false,
    repliesCount: 15,
    reposts: 12,
    reposted: false,
    hasImage: true,
    imageSrc: "dot_character.png",
    imageAlt: "自作のドット絵キャラクター",
    avatarColor: "from-amber-400 to-yellow-500",
    hasCollabButton: true,
    heartsTotal: 890,
    replies: [
      { id: 109, name: "名無しRt3", content: "かわいい！使っていい？", time: "1日前" },
      { id: 110, name: "名無しUv6", content: "ドット絵いいな、僕も始めよう", time: "1日前" }
    ]
  },
  {
    id: 7,
    name: "名無しNe4",
    time: "3日前",
    content: "今週のお題「青空」に参加\nみんなの投稿も見に行こう",
    likes: 12,
    dislikes: 0,
    liked: false,
    disliked: false,
    repliesCount: 4,
    reposts: 0,
    reposted: false,
    hasImage: true,
    imageSrc: "blue_sky.jpg",
    imageAlt: "青空と雲の写真",
    avatarColor: "from-cyan-400 to-indigo-500",
    hasCollabButton: true,
    heartsTotal: 67,
    replies: []
  },
  {
    id: 8,
    name: "名無しXz9",
    time: "4日前",
    content: "#お絵描き\n描きためたイラストまとめ\n今月は10枚描けたぞ",
    likes: 89,
    dislikes: 2,
    liked: false,
    disliked: false,
    repliesCount: 22,
    reposts: 15,
    reposted: false,
    hasImage: true,
    imageSrc: "illust_summary.png",
    imageAlt: "今月描いたイラスト集",
    avatarColor: "from-pink-400 to-rose-500",
    hasCollabButton: true,
    heartsTotal: 1250,
    replies: [
      { id: 111, name: "名無しAs5", content: "全部素敵！特に3枚目が好き", time: "3日前" },
      { id: 112, name: "名無しDf9", content: "ペースすごいな、尊敬する", time: "3日前" },
      { id: 113, name: "名無しGh2", content: "もっと見たいです！", time: "2日前" }
    ]
  }
];
